import React, { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { Clock, Users, CalendarDays, Loader2, RefreshCw, BarChart3 } from "lucide-react";

// Shows the automated per-club monthly reports (court hours + active players)
// generated by the Monthly Club Report workflow. Club owners can also trigger a
// fresh report for the previous month on demand.
export default function MonthlyReportsPanel() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const all = await base44.entities.ClubMonthlyReport.list("-period_month", 100);
      setReports(all);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const generate = async () => {
    setGenerating(true);
    try {
      await base44.functions.invoke("generate-club-monthly-report", {});
      await load();
    } finally {
      setGenerating(false);
    }
  };

  return (
    <section className="rounded-2xl border border-white/5 bg-white/[0.03] p-5">
      <div className="flex items-center justify-between gap-3 mb-4">
        <div>
          <h2 className="font-display text-lg font-semibold text-white flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-lime-400" /> Monthly reports
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Auto-generated on the 1st of each month — court hours used and active players.
          </p>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={generating}
          className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-lime-400/15 hover:bg-lime-400/25 text-lime-300 border border-lime-400/20 text-sm font-medium transition disabled:opacity-60"
        >
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
          {generating ? "Generating…" : "Generate now"}
        </button>
      </div>

      {loading ? (
        <div className="flex justify-center py-8">
          <Loader2 className="w-5 h-5 animate-spin text-slate-400" />
        </div>
      ) : reports.length === 0 ? (
        <p className="text-sm text-slate-400 text-center py-8">
          No reports yet. They generate automatically on the 1st, or tap “Generate now”.
        </p>
      ) : (
        <div className="space-y-3">
          {reports.map((r) => (
            <div
              key={r.id}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <div className="flex items-center justify-between gap-2 mb-3">
                <div className="min-w-0">
                  <div className="text-white font-semibold truncate">{r.club_name}</div>
                  <div className="flex items-center gap-1.5 text-xs text-slate-400">
                    <CalendarDays className="w-3.5 h-3.5" /> {r.period_month}
                  </div>
                </div>
                <span className="text-[11px] text-slate-500 shrink-0">
                  {r.generated_at ? new Date(r.generated_at).toLocaleDateString() : ""}
                </span>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <Metric icon={<Clock className="w-4 h-4 text-lime-400" />} label="Court hours" value={r.total_court_hours} />
                <Metric icon={<Users className="w-4 h-4 text-emerald-400" />} label="Active players" value={r.active_players} />
                <Metric icon={<CalendarDays className="w-4 h-4 text-sky-400" />} label="Events" value={r.events_count} />
                <Metric icon={<BarChart3 className="w-4 h-4 text-amber-400" />} label="Plays" value={r.plays_count} />
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

function Metric({ icon, label, value }) {
  return (
    <div className="rounded-lg bg-white/[0.03] px-3 py-2">
      <div className="flex items-center gap-1.5 text-[11px] text-slate-400 mb-0.5">{icon}{label}</div>
      <div className="text-white font-semibold text-lg leading-tight">{value ?? 0}</div>
    </div>
  );
}